[package]
name = "idiomatic"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.41.0", features = ["full"] }
log = "0.4.22"
simple_logger = "5.0.0"

[lints.rust]
unsafe_code = "forbid"

[[example]]
name = "cli"
path = "./examples/cli/src/main.rs"
